name: Periodic jobs

# on:
#   schedule:
#     - cron: '50 1 * * *'
on:
  push:
    branches:
      - master

jobs:
  health_check:
  - name: Check the deployed service URL
    uses: jtalk/url-health-check-action@v3
    with:
      url: https://pokedex-ci-cd-7ipc.onrender.com/health
        max-attempts: 3
        retry-delay: 5s

